# Site settings
name: Less Or More
email: xiaobooluo@qq.com
author: xiaobo
url: http://xiaobooluo.github.io
resume_site: 
github: https://github.com/xiaobooluo
baseurl: ""
description: Actually, less is more!
meta_description: 代码之路，记录风景
motto: make it beautiful
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
gems: [jekyll-paginate]
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : xiaobo
    duoshuo:
        short_name : xx
    disqus :
        short_name : xx
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light